[BE] feat(#97): Todo crud api
DKU-Dgaja/gitudy pull request #105
Opened 2024-02-06 12:49 UTC by j-ra1n

## #️⃣ 연관된 이슈

#97 

### Pull Request Type

어떤 변경 사항이 있나요?

- [x]  새로운 기능 추가
- [ ]  코드 리팩토링
- [ ]  버그 수정
- [ ]  CSS 등 사용자 UI 디자인 변경
- [ ]  테스트 추가, 테스트 리팩토링
- [ ]  코드에 영향을 주지 않는 변경사항
    - 오타 수정, 문서 수정, 변수명 변경, 주석 추가 및 수정

### Pull Request Checklist

PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x]  변경 사항에 대한 테스트를 모두 통과했나요?
- [x]  코드 정렬은 적용했나요?
- [x]  새로운 branch에 작업 후 dev로 PR을 요청했나요?

## 📝 작업 내용

api
Todo 등록
Todo 조회
Todo 수정
Todo 삭제

## 💬 리뷰 요구사항

Todo 삭제할때 TodoId로만 삭제해도 되는지 궁금하네요 중복된 TodoId도 있을거같아서 userId랑 같이 받아와서 삭제해야하는지,,

피드백부탁드립니다 🌵

2024-02-07 07:17 UTC, jusung-c requested changes
수고하셨습니다~~
리뷰가 정확하지 않을 수 있다는 점.. 이해해주시고 이상하다 싶은 거 바로 물어봐주세요!!

2024-02-07 07:17 UTC, jusung-c commented on backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
> +    @Transactional
@Transactional을 언제 붙이면 좋을지 공부해보면 좋을 것 같아요~

2024-02-07 07:17 UTC, jusung-c commented on backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
> +        studyTodoMappingRepository.save(studyTodoMapping);
save() 호출이 필요할까요? JPA 영속성 컨텍스트에 대해 공부해보면 좋을 것 같아요!

2024-02-07 07:17 UTC, jusung-c commented on backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
> +        studyTodoMappingRepository.deleteAll(todoMapping);
제가 알기론 그냥 deleteByTodoId()로 해도 관련된 레코드가 전부 삭제되고 반환값으로 삭제된 레코드의 개수를 받을 수 있어요. 한번 찾아보셔도 좋을 것 같아요!

2024-02-07 07:17 UTC, jusung-c commented on backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
> +
저라면 조회시 null인 경우 예외 처리를 해줄 것 같긴 해요. 구현하신 코드는 null을 방지할 수 있어서 좋은 코드인 것 같아요. 하지만 삭제된 줄 알고 있었는데 알고보니 todoId가 잘못된 값이라 존재하지 않아서 삭제되지 않았는데 모르고 넘어갈 수도 있다는 혹시 모를 상황에 대비해..

2024-02-08 02:30 UTC, j-ra1n commented on backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
> +        studyTodoService.registerStudyTodo(studyTodo, studyTodoMapping);
컨트롤러에서 가져온 userId와 StudyTodoRepository에 저장된 userId와 같은지 비교하는걸로 수정하겠습니다!

2024-02-08 04:03 UTC, jusung-c commented on backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
> +        studyTodoService.updateStudyTodo(todoId, request, user.getId());
시큐리티에 User 정보를 저장할 때 id를 지정하지 않아요 그래서 userPrincipal.getId() 이렇게 하면 null 값이 나올거에요. 

아래는 필터에서 시큐리티에 User를 저장하는 로직인데요. 이 값들 중 유니크 값들을 이용해 일치하는 DB의 User를 찾아야 할 것 같아요. 
<img width="545" alt="image" src="https://github.com/DKU-Dgaja/gitudy/assets/62228433/fca1d877-31d5-43a0-a780-000d1dc9ff1b">

2024-02-12 05:42 UTC, ghdcksgml1 reviewed
고생하셨습니다 😁 비즈니스 로직을 신경쓴게 보이네용

다른 예외 케이스는 없을지 외래키로 설정되어있는 테이블들을 유심히 살펴보시면 좋을 것 같네용

2024-02-12 05:42 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
> +        studyTodoService.registerStudyTodo(studyTodo, studyInfoId, user.getId());
위 로직들은 Service 영역에서 맡아야할 로직들 같아요! Controller는 데이터의 흐름제어 용도로만 사용합시다!

2024-02-12 05:42 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
> +
todoId에 매칭되는 값이 있는지도 체크하면 좋을 것 같네여

2024-02-28 11:12 UTC, closed without merging