Feat(#47) refresh token 생성 및 저장 구현
DKU-Dgaja/gitudy pull request #48
Opened 2024-01-20 10:51 UTC by rndudals

## #️⃣ 연관된 이슈

ex) #이슈번호

### Pull Request Type

어떤 변경 사항이 있나요?

- [ ]  새로운 기능 추가
- [ ]  코드 리팩토링
- [ ]  버그 수정
- [ ]  CSS 등 사용자 UI 디자인 변경
- [ ]  테스트 추가, 테스트 리팩토링
- [ ]  코드에 영향을 주지 않는 변경사항
    - 오타 수정, 문서 수정, 변수명 변경, 주석 추가 및 수정

### Pull Request Checklist

PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ]  변경 사항에 대한 테스트를 모두 통과했나요?
- [ ]  코드 정렬은 적용했나요?
- [ ]  새로운 branch에 작업 후 dev로 PR을 요청했나요?

## 📝 작업 내용

* Refresh Token 생성 함수 추가
* Refresh Token redis에 저장
* Refresh Token 관련 테스트
## 💬 리뷰 요구사항
피드백 부탁드립니다~~

2024-01-20 11:07 UTC, rndudals commented
1. Refresh Token 발급
<img width="1193" alt="스크린샷 2024-01-20 182232" src="https://github.com/DKU-Dgaja/gitudy/assets/102203336/0681e0b2-83dd-4916-8148-094123e0673c">



2. Refresh Token을 redis에 저장
<img width="551" alt="스크린샷 2024-01-20 184403" src="https://github.com/DKU-Dgaja/gitudy/assets/102203336/18dc8791-fccc-4103-acc7-13c9d1ab6f18">






3. Test
<img width="450" alt="스크린샷 2024-01-20 194239" src="https://github.com/DKU-Dgaja/gitudy/assets/102203336/2da5af8e-9eb4-4c43-9b63-7d6d50460f39">

<img width="447" alt="스크린샷 2024-01-20 194324" src="https://github.com/DKU-Dgaja/gitudy/assets/102203336/3db3834a-9290-41d4-9be7-50cba670cb76">

<img width="452" alt="스크린샷 2024-01-20 194409" src="https://github.com/DKU-Dgaja/gitudy/assets/102203336/50fcde37-9d99-4923-b88b-3b2b7c4a04e3">

2024-01-21 02:03 UTC, ghdcksgml1 requested changes
전체적으로 로직들을 잘 짜셨네요 ㅎㅎ 코멘트 남긴부분 잘 처리해주세요 🤓

2024-01-21 02:03 UTC, ghdcksgml1 commented on backend/src/test/java/com/example/backend/auth/api/service/token/RefreshTokenServiceTest.java
> +        assertThat(testToken.get().getEmail()).isEqualTo("TestEmail@test.com");
입력과 검증 값은 변수로 빼주시면 좋을 것 같습니다 😄 **(가스라이팅)**

2024-01-21 05:38 UTC, jusung-c commented on backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
> +        refreshTokenService.saveRefreshToken(new RefreshToken(jwtRefreshToken, user.getEmail()));
builder() 패턴 사용해서 객체 생성하면 가독성이 더 향상될 것 같아요!

2024-01-22 02:30 UTC, rndudals commented
피드백 반영했습니다 확인해주세요~~

2024-01-23 01:35 UTC, jusung-c approved these changes
수고하셨습니다😎

2024-01-23 21:18 UTC, ghdcksgml1 approved these changes

2024-01-24 00:20 UTC, merged