Feat(#46) state verification
DKU-Dgaja/gitudy pull request #56
Opened 2024-01-21 04:47 UTC by j-ra1n

## #️⃣ 연관된 이슈

#46 

### Pull Request Type

어떤 변경 사항이 있나요?

- [x]  새로운 기능 추가
- [ ]  코드 리팩토링
- [ ]  버그 수정
- [ ]  CSS 등 사용자 UI 디자인 변경
- [x]  테스트 추가, 테스트 리팩토링
- [ ]  코드에 영향을 주지 않는 변경사항
    - 오타 수정, 문서 수정, 변수명 변경, 주석 추가 및 수정

### Pull Request Checklist

PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x]  변경 사항에 대한 테스트를 모두 통과했나요?
- [x]  코드 정렬은 적용했나요?
- [x]  새로운 branch에 작업 후 dev로 PR을 요청했나요?

## 📝 작업 내용

* State 저장,검증,삭제 구현

## 💬 리뷰 요구사항

피드백 부탁드립니다!!

2024-01-21 04:51 UTC, j-ra1n commented
1.  실제 state 생성확인
![KakaoTalk_20240121_131810358](https://github.com/DKU-Dgaja/gitudy/assets/118893707/d972aa60-a1f5-4b40-a188-162e896d84ae)

2. state 삭제 주석 추가하여 저장 확인
![KakaoTalk_20240121_131818629](https://github.com/DKU-Dgaja/gitudy/assets/118893707/f010eaea-780e-4625-843e-5a2ff02947ed)

3. test 로직으로 확인
![KakaoTalk_20240121_134432945](https://github.com/DKU-Dgaja/gitudy/assets/118893707/2e26251c-09c7-4935-a47b-40d31a22c5c0)

4. 삭제 확인
![KakaoTalk_20240121_134456590](https://github.com/DKU-Dgaja/gitudy/assets/118893707/6b83b1b2-c231-47f5-903f-5307f00f8b87)

2024-01-21 06:08 UTC, jusung-c reviewed
수고하셨습니당~

2024-01-21 06:08 UTC, jusung-c commented on backend/src/main/java/com/example/backend/domain/define/state/LoginState.java
> +        this.state=UUID.randomUUID();
state 필드에 달아준 `@Id` 어노테이션 덕에 자동으로 UUID가 생성되어 관리될 것 같아요 
따로 randomUUID를 넣어주지 않아도 될 것 같습니다!

2024-01-21 07:54 UTC, ghdcksgml1 requested changes
코드 잘 짜고 계시네요 ㅎㅎ 언급한 부분만 조금 살펴봐주세요 😁

혹시나 다른 의견이 있다면 같이 토론해봐요!

2024-01-21 07:54 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/domain/define/state/LoginState.java
> +    private UUID state;  // state 검증
개인적으로 UUID보다는 String으로 바꾸는것을 추천드려요!!

어차피 UUID형태로 내부적으로 id가 생성되고, 조회시에도 더 편할 것 같네요 😁

2024-01-21 07:54 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/domain/define/state/LoginState.java
> +    private  boolean isUse; // 사용 가능 여부
isUse 필드가 굳이 존재할 필요가 없어보이긴 합니다! 사용하고 나면 삭제하기 때문에 boolean 필드로써의 기능을 하지는 못할 것 같네요 ㅎㅎ

2024-01-21 09:22 UTC, j-ra1n commented
피드백 반영했씁니다~~ 

1. isUSe 필드가 현재 LoginStateService 에서  // 로그인 상태가 더이상 유효하지 않은 경우 예외 처리에 쓰이고 있는데 예외 처리 부분을 빼고 isUse 필드도 삭제하는 것이 좋을까요??

2024-01-21 09:37 UTC, j-ra1n commented
피드백 반영했씁니다~~ @jusung-c   @ghdcksgml1  

1. isUSe 필드가 현재 LoginStateService 에서  // 로그인 상태가 더이상 유효하지 않은 경우 예외 처리에 쓰이고 있는데 예외 처리 부분을 빼고 isUse 필드도 삭제하는 것이 좋을까요??

2024-01-22 00:36 UTC, jusung-c commented
isUse 필드가 유의미하게 사용될만한 상황을 생각해봤는데 로그인페이지 요청 후 state가 발급되었을 때 그 state값으로 로그인 요청을 시도하면 그 때 isUse 필드를 "사용중" 상태로 바꿔주고 이후에 state 만료시간 안에 동일한 state 값으로 로그인을 요청하는 걸 막기 위한 경우가 있을 것 같네요!  아마??

근데 저희는 state 값의 만료시간을 3분으로 짧게 설정해서 이정도로 충분하지 않나 생각해 봄미다

2024-01-22 00:57 UTC, jusung-c commented
아 착각했습니다. 어차피 사용하자마자 바로 삭제해버리니 상관없네요 ㅎㅎ..

2024-01-22 03:51 UTC, jusung-c commented
넵 저희가 따로 false로 변경해주는 로직이 없었어서 예외도 없을 것 같습니닷

2024-01-22 06:12 UTC, j-ra1n commented
넵 변경했습니다~~

2024-01-23 01:18 UTC, jusung-c approved these changes
수고하셨습미다🔥

2024-01-23 21:16 UTC, ghdcksgml1 approved these changes
사용하지 않는 테스트는 삭제해주세요 😁

2024-01-23 21:16 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
> +    OAUTH_CONFIG_NULL("application.yml 파일에서 속성 값을 읽어오지 못했습니다."),
시스템 정보에 관한 에러를 클라이언트에게 내려주는건 맞지 않아보입니다!

2024-01-24 00:49 UTC, merged