[BE] Feat: (#64) jwt 재발급 구현
DKU-Dgaja/gitudy pull request #75
Opened 2024-01-26 08:15 UTC by rndudals

## #64

### Pull Request Type

어떤 변경 사항이 있나요?

- [x]  새로운 기능 추가
- [x]  코드 리팩토링
- [ ]  버그 수정
- [ ]  CSS 등 사용자 UI 디자인 변경
- [ ]  테스트 추가, 테스트 리팩토링
- [ ]  코드에 영향을 주지 않는 변경사항
    - 오타 수정, 문서 수정, 변수명 변경, 주석 추가 및 수정

### Pull Request Checklist

PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x]  변경 사항에 대한 테스트를 모두 통과했나요?
- [x]  코드 정렬은 적용했나요?
- [x]  새로운 branch에 작업 후 dev로 PR을 요청했나요?

## 📝 작업 내용
### Feat
 JWT 재발급 로직 구현
* AuthController : /reissue 컨트롤러 구현
* ReissueAccessTokenResponse : DTO 구현
* AuthService : 재발급을 위한 서비스 구현
* RefreshTokenService : 재발급을 위한 reissue() 추가
* ExceptionMessage 추가
* RefreshTokenServiceTest :  JWT_NOT_EXIST_RTK 예외 발생 Test
### Refactor
platformId -> Subject 변경

## 💬 리뷰 요구사항
피드백 부탁드립니다~

2024-01-26 08:24 UTC, rndudals commented
1. 재발급 전

<img width="1193" alt="스크린샷 2024-01-26 151825" src="https://github.com/DKU-Dgaja/gitudy/assets/102203336/0a18b0e6-694b-42e5-9bf4-a110f59e2612">



2. 재발급 중


<img width="951" alt="스크린샷 2024-01-26 152103" src="https://github.com/DKU-Dgaja/gitudy/assets/102203336/88bd8064-74d2-400a-a5c7-1abc44448709">


3. 재발급 후 accesstoken 변경




<img width="1127" alt="스크린샷 2024-01-26 152041" src="https://github.com/DKU-Dgaja/gitudy/assets/102203336/c1bf17b7-c226-4f08-a5c5-212179eda7b4">

2024-01-27 02:04 UTC, ghdcksgml1 requested changes
잘 구현하셨네요 ㅎㅎㅎ 한가지 궁금한 점은

현재 JWT Token에 name, profileURL같은 정보들을 담고 있는데, 유저가 프로필 변경을 했을 경우에 토큰에 반영되지 못할 것 같은데

Reissue에서 토큰을 재발행 해줄때 유저 데이터베이스에 접근해서 데이터베이스에 저장되어 있는 정보로 재발행을 해주는 로직으로 만들어, 유저 프로필 변경 시 토큰을 재발급해야하는 로직을 추가하는걸 프론트에 요청한다거나,

아니면, platformType, id처럼 변경되지 않을 값들만 Token에 넣어주는 방법 등을 고려해봐야할 것 같아요

2024-01-27 02:04 UTC, ghdcksgml1 commented on backend/src/test/java/com/example/backend/auth/api/service/token/RefreshTokenServiceTest.java
> +        String testSubject = "KAKAO_1234";
검증할 값들을 변수로 빼주는거 너무 좋습니다! 😁

2024-01-27 02:23 UTC, rndudals commented on backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
> +            ReissueAccessTokenResponse reissueResponse = authService.reissueAccessToken(tokens.get(2));
헤더 형태가 정확히 어떻게 되는지 잘 모르겠습니다. 제 생각은 [Bearer] [토큰] 이렇게 하면 token.size()가 2가 나와야하는데 3이 나오는거 보면 [???] [Bearer] [token] 이런 형태로 되어있다는 건데 [???] 이 부분에는 뭐가 들어있는건가요????

2024-01-27 02:24 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
> +            ReissueAccessTokenResponse reissueResponse = authService.reissueAccessToken(tokens.get(2));
Bearer accesstoken refreshtoken으로 되어있습니다!

2024-01-27 03:10 UTC, jusung-c commented on backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
> +            ReissueAccessTokenResponse reissueResponse = authService.reissueAccessToken(tokens.get(2));
현재 JWT 토큰 검증 필터에 Bearer accesstoken refreshtoken 형식으로 변경이 안되어있어서 변경해주셔야 할 것 같아요!!

2024-01-27 12:13 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/auth/api/service/token/RefreshTokenService.java
> +        }
access Token을 만들어주는건 AuthService의 역할인데 RefreshTokenService에서 accessToken까지 만들어주는 역할을 하고 있는 것 같네요

RefreshTokenService에서는 유저가 요청한 RefreshToken이 레디스에 있는지 정도만 체크하는게 맞아 보여요!

@jusung-c  개인적으로는 AuthService에서 generateJwtToken이 아니라, generateAccessToken, generateRefreshToken으로 메소드를 2개로 분리하면, AccessToken 갱신 작업 시에도 generateAccesToken메소드를 재사용할 수 있을 것 같다는 생각이 드네요.

2024-01-27 12:13 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/auth/api/service/token/RefreshTokenService.java
> +                UserPlatformType.valueOf(platformType)).get();
Optional을 get()으로 바로 받아오신 이유가 있을까요??

2024-01-27 12:13 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
> +    private final static int ACCESS_TOKEN_INDEX = 2;
2번 인덱스는 RefreshToken 입니다!

- 0 : Bearer
- 1 : Access Token
- 2 : Refresh Token

2024-01-27 12:13 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java
> +            authenticateUserWithJwtToken(subject, reissueAccessToken, request);
AccessToken이 만료되면, Refresh Token으로 Access Token 대신 사용자 인증을 진행하는 코드로 보이는데

의도하신 방향이 맞을까용??

개인적으로는 Header로 토큰을 받고있기 때문에 ExpiredJwtException에서 바로 재발행을 해주는 방향보다는, 에러를 그대로 내주면서, 프론트에서 Reissue를 호출하도록 유도하는 방법이 나을 것 같다는 생각입니다 😁

2024-01-27 14:12 UTC, rndudals commented on backend/src/main/java/com/example/backend/auth/api/service/token/RefreshTokenService.java
> +                UserPlatformType.valueOf(platformType)).get();
없습니다!! 빼버릴까요??

2024-01-27 14:17 UTC, rndudals commented on backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java
> +            authenticateUserWithJwtToken(subject, reissueAccessToken, request);
AccessToken이 만료되면, Refresh Token을 사용해서 Access Token을 재발급한 후 시큐리티에 등록하는 의도로 짰습니다!!

JWT_TOKEN_EXPIRED 에러를 내주면서 프론트에 Reissue 호출하도록 유도하는 방법을 어떻게하는지 조금 자세하게 알 수 있을까요????

2024-01-27 14:23 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java
> +            authenticateUserWithJwtToken(subject, reissueAccessToken, request);
Access Token은 프론트에서 들고 있는 값이라서 백엔드에서 값을 바꿔주더라도 요청하는 Access Token은 변하지 않아서

토큰 만료 오류가 발생할때 그대로 오류를 내보내주면, 프론트에서 토큰을 재발행하는 API를 호출해 재발행 받은 Access Token으로 요청하게 하는 방법입니다!

2024-01-27 14:32 UTC, rndudals commented on backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java
> +            authenticateUserWithJwtToken(subject, reissueAccessToken, request);
백에서는 토큰이 만기되었다는 오류만 내주고 나머지는 프론트에 토큰이 만기 되었다는 에러가 뜨면 reissue를 호출하면 된다고 알려주면 되는건가요?? 아니면 reissue쪽으로 리다이렉트를 해줘야하나요??

2024-01-27 14:41 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java
> +            authenticateUserWithJwtToken(subject, reissueAccessToken, request);
리다이렉트까진 필요없어보입니다!

2024-01-27 14:51 UTC, jusung-c commented on backend/src/main/java/com/example/backend/auth/api/service/token/RefreshTokenService.java
> +        }
역할도 구분하고 재사용성도 높이고 체고네요!! 저도 분리해서 진행하면 좋을 것 같아요!

2024-01-27 14:54 UTC, rndudals commented on backend/src/main/java/com/example/backend/auth/api/service/token/RefreshTokenService.java
> +        }
역할을 분리해보겠습니다👍🏻👍🏻

2024-01-28 08:21 UTC, rndudals commented
## 1. 토큰이 만료되기전 AccessToken으로 인증 성공

<img width="356" alt="스크린샷 2024-01-28 164744" src="https://github.com/DKU-Dgaja/gitudy/assets/102203336/fa05889b-9843-4453-b0e9-b2185e4f42a1">


<img width="250" alt="스크린샷 2024-01-28 164754" src="https://github.com/DKU-Dgaja/gitudy/assets/102203336/58b21278-c485-4704-830c-f8547318f44a">


## 2. 토큰이 만료된 후 1번의 URL로 재요청
<img width="335" alt="스크린샷 2024-01-28 171711" src="https://github.com/DKU-Dgaja/gitudy/assets/102203336/eb7857d0-9036-41fd-8bf6-4b088ad35d0c">




## 3. reissue 호출로 access token 재발급

<img width="530" alt="스크린샷 2024-01-28 165041" src="https://github.com/DKU-Dgaja/gitudy/assets/102203336/60af290d-3b6a-42f0-9457-f7323951bc4d">

<img width="296" alt="스크린샷 2024-01-28 171729" src="https://github.com/DKU-Dgaja/gitudy/assets/102203336/d2622509-4dec-478d-88bc-20c9f01e56e1">




## 4. claim정보 변경 후 모든 테스트 통과
<img width="538" alt="스크린샷 2024-01-28 170226" src="https://github.com/DKU-Dgaja/gitudy/assets/102203336/6a3f2330-6770-4c25-9d8e-9785ac55ab3e">

2024-01-28 09:40 UTC, ghdcksgml1 approved these changes
제가 요구한게 넘 많았는데 고생 넘 많으셨습니다 😅

2024-01-28 09:47 UTC, rndudals commented
이러 피드백 너무 좋습니다 ㅎㅎ 성장하는 느낌입니다 ㅎㅎ

2024-01-28 11:24 UTC, j-ra1n approved these changes

2024-01-28 12:21 UTC, merged