[BE] feat(#61): logout 구현
DKU-Dgaja/gitudy pull request #76
Opened 2024-01-26 13:49 UTC by j-ra1n

## #️⃣ 연관된 이슈

#61 

### Pull Request Type

어떤 변경 사항이 있나요?

- [x]  새로운 기능 추가
- [ ]  코드 리팩토링
- [ ]  버그 수정
- [ ]  CSS 등 사용자 UI 디자인 변경
- [x]  테스트 추가, 테스트 리팩토링
- [ ]  코드에 영향을 주지 않는 변경사항
    - 오타 수정, 문서 수정, 변수명 변경, 주석 추가 및 수정

### Pull Request Checklist

PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ]  변경 사항에 대한 테스트를 모두 통과했나요?
- [x]  코드 정렬은 적용했나요?
- [x]  새로운 branch에 작업 후 dev로 PR을 요청했나요?

## 📝 작업 내용

Logout 구현 (redis에 저장된 refreshtoken 삭제)

## 💬 리뷰 요구사항

AuthControllerTest에서 "로그아웃 성공 테스트"
부분이 해결이 안됐는데 더 좋은 테스트 방법이 있는지 다른 해결방법이 있는지도 피드백 부탁드립미다...

2024-01-27 01:55 UTC, ghdcksgml1 requested changes
잘하구 계시네요 ㅎㅎ 리뷰 요청드린거 참고해주세용 !!

추가로, @AuthenticationPrincipal 어노테이션에 대해서도 공부해보심 좋을 것 같습니다!

2024-01-27 01:55 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
> +        List<String> tokens = Arrays.asList(token.split(" "));
split 함수를 쓰면 String의 배열로 리턴을 해주는데 리스트로 바꾸신 이유가 있을까요??

> 같은 형태처럼 보여서 특별히 사용하신 이유가 있는지 궁금합니다 😁

2024-01-27 01:55 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
> +            authService.logout(tokens.get(2));  // refresh token
https://github.com/DKU-Dgaja/gitudy/pull/22#discussion_r1444564497 이 부분은 해당 커맨트 참고해서 리팩토링 해주시면 좋을 것 같아요!! 😁

단순 인덱스로 접근하는게 아닌 상수로 정의해서 선언한다면, 옆에 주석도 필요없어지겠죠? ㅎㅎ

2024-01-27 01:55 UTC, ghdcksgml1 commented on backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
> +                        .header("Authorization", "Bearer " + accessToken))
해당 부분 NullPointerException이 발생할 것 같은데 성공하나요?? Github Action에서도 테스트가 깨진 것 같네요!

2024-01-28 05:19 UTC, j-ra1n commented on backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
> +        List<String> tokens = Arrays.asList(token.split(" "));
어.. 리스트가 작업하기 편하고 get이나 size 메소드를 쓰면 가독성이 향샹된다고 어디서 본거같은... ㅎㅎ String [] tokens 으로 바꿀까요?

2024-01-28 05:31 UTC, j-ra1n commented on backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
> +                        .header("Authorization", "Bearer " + accessToken))
맞아요 이부분 형식이 잘못된건지 "Bearer" + accessToken + refreshToen 으로 해도 오류가 나서 어찌해야할지 모르겠어여 😢

2024-01-28 05:51 UTC, j-ra1n commented on backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
> +                        .header("Authorization", "Bearer " + accessToken))
> 맞아요 이부분 형식이 잘못된건지 "Bearer" + accessToken + refreshToen 으로 해도 오류가 나서 어찌해야할지 모르겠어여 😢

"Bearer" + " " + accessToken + " " + refreshToken 으로 변경해서 완료해씁니다~~

2024-01-28 05:53 UTC, j-ra1n commented on backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
> +                        .header("Authorization", "Bearer " + accessToken))
![image](https://github.com/DKU-Dgaja/gitudy/assets/118893707/5146f977-dbcf-43e0-8425-4dcd15d28d98)

2024-01-28 06:23 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
> +        List<String> tokens = Arrays.asList(token.split(" "));
편하신 대로 하시는게 맞는 것 같아요 😁

2024-01-28 06:31 UTC, ghdcksgml1 commented on backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
> +@SpringBootTest
위 두개 어노테이션은 TestConfig에 존재해서 빼셔두 될 것 같네용!

2024-01-28 06:31 UTC, ghdcksgml1 commented on backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
> +        userRepository.deleteAllInBatch();
현재 Redis도 접근하고 계신데 Redis Repository도 초기화해주세요!

2024-01-28 06:31 UTC, ghdcksgml1 commented on backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
> +                        .header("Authorization", "Bearer" + " " + accessToken + " " + refreshToken))
테스트할때마다 `"Bearer" + " " + accessToken + " " + refreshToken` 이렇게 조합해서 써야하는 번거로움이 존재하는데,

이 부분을 TestConfig에 static 메소드로 만들어서 모두가 편하게 사용할 수 있도록 만들어주는건 어떨까요? 😄

`Authorization` 문자열도 상수로 빼면, 문자열을 잘못입력함으로써 발생하는 테스트 오류를 피할 수 있을 것 같네요

2024-01-28 09:36 UTC, j-ra1n commented on backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
> +                        .header("Authorization", "Bearer" + " " + accessToken + " " + refreshToken))
피드백 반영했습니다!

2024-01-28 09:37 UTC, j-ra1n commented on backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
> +        userRepository.deleteAllInBatch();
Redis 어디말씀하시는건지 모르겠어요.. 😮

2024-01-28 09:38 UTC, ghdcksgml1 approved these changes

2024-01-28 11:22 UTC, merged