[BE] feat(#39): 유저 정보 조회
DKU-Dgaja/gitudy pull request #84
Opened 2024-01-31 08:28 UTC by j-ra1n

## #️⃣ 연관된 이슈

#39 

### Pull Request Type

어떤 변경 사항이 있나요?

- [x]  새로운 기능 추가
- [ ]  코드 리팩토링
- [ ]  버그 수정
- [ ]  CSS 등 사용자 UI 디자인 변경
- [x]  테스트 추가, 테스트 리팩토링
- [ ]  코드에 영향을 주지 않는 변경사항
    - 오타 수정, 문서 수정, 변수명 변경, 주석 추가 및 수정

### Pull Request Checklist

PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ]  변경 사항에 대한 테스트를 모두 통과했나요?
- [x]  코드 정렬은 적용했나요?
- [x]  새로운 branch에 작업 후 dev로 PR을 요청했나요?

## 📝 작업 내용

* @AuthenticationPrincipal 어노테이션 사용 -> (인증된 사용자의 정보)
* user info DTO 추가
* 예외 메시지 추가
* 테스트 추가

## 💬 리뷰 요구사항

유저정보 조회 성공 테스트가 안되고있는데 일단 res_code가 400이 나오고 res_obj는 null 이라 불러와져서..
갈피를 못잡고 있습니다..!

2024-01-31 09:50 UTC, j-ra1n commented
![image](https://github.com/DKU-Dgaja/gitudy/assets/118893707/1af9e314-55e2-490d-8823-2e1443626060)

2024-01-31 10:21 UTC, jusung-c commented on backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
> +        return JsonResult.successOf(UserInfoResponse.of(user));
@AuthenticationPrincipal로 세션에 저장된 User 정보를 가져왔는데 이 정보로는 필요한 정보들을 다 얻을 수 없을 것 같아요. DB에 있는 User에 접근해서 정보를 가져오는 로직이 필요하지 않을까 생각해봅미다~

2024-01-31 11:39 UTC, rndudals commented
1. 컨트롤러를 최대한 간단하게 하고 나머지 로직들을 UserService로 넘기는게 나을 것 같아요! 
2. AuthController에서 로직을 처리하는거여서 UserService 클래스를 따로 생성하는 것보다 AuthService안에 getUserByPlatform() 함수를 구현하는게 좋을 것 같습니다!

2024-01-31 15:43 UTC, j-ra1n commented
* authService를 @MockBean로 주입하면
    @DisplayName("유저정보 조회 성공 테스트")에서 오류나면서 실패함
         -> 디버깅 해보니 AuthController의  @GetMapping("/info") 부분에서 getUserByInfo 함수 호출이 안됩니다.

authService를 @Autowired로 주입하면
함수 호출이 잘되고 [유저정보 조회 성공 테스트 ]성공합니다.
하지만  [로그아웃 성공 테스트] 은 실패합니다.

이유를 모르겠습니다.

2024-02-01 01:03 UTC, jusung-c commented
@MockBean 테스트는 가짜 객체를 넣어주는 테스트여서 실제 작동을 하지 않는 걸로 알고 있어욥.
AuthControllerTest는 컨트롤러 단을 테스트하는 것이므로 when() 메서드를 통해 authService의 동작을 지정해준 후 테스트를 진행하면 될 것 같아요~

authService 동작에 대한 테스트는 AuthServiceTest에서 진행하시면 될 것 같아요!

2024-02-01 07:26 UTC, jusung-c requested changes

2024-02-01 07:26 UTC, jusung-c commented on backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
> +    USER_NOT_FOUND("데이터베이스에서 사용자를 찾을 수 없습니다.")
User 관련 Exception을 처리할 커스텀 Exception 클래스도 만들어주세요!

2024-02-01 07:26 UTC, jusung-c commented on backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
> +        User user = userRepository.findByPlatformIdAndPlatformType(platformId, platformType).orElse(null);
조회할 때 없는 경우 null을 넣어주기보다는 바로 예외를 터뜨려주는 게 좋아보여요. 이렇게 하면 컨트롤러에서 if문도 없앨 수 있을 것 같아요

2024-02-01 07:49 UTC, j-ra1n commented
예외확인
![image](https://github.com/DKU-Dgaja/gitudy/assets/118893707/513ccf9e-3920-40be-b537-84b1e1fb6c34)

2024-02-01 12:12 UTC, jusung-c approved these changes

2024-02-01 12:12 UTC, ghdcksgml1 approved these changes

2024-02-01 12:44 UTC, merged