[BE] feat(#96): 마이 커밋 조회 api 구현
DKU-Dgaja/gitudy pull request #98
Opened 2024-02-04 09:50 UTC by jusung-c

## #️⃣ 연관된 이슈
#96 

### Pull Request Type

어떤 변경 사항이 있나요?

- [x]  새로운 기능 추가
- [ ]  코드 리팩토링
- [ ]  버그 수정
- [ ]  CSS 등 사용자 UI 디자인 변경
- [ ]  테스트 추가, 테스트 리팩토링
- [ ]  코드에 영향을 주지 않는 변경사항
    - 오타 수정, 문서 수정, 변수명 변경, 주석 추가 및 수정

### Pull Request Checklist

PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x]  변경 사항에 대한 테스트를 모두 통과했나요?
- [x]  코드 정렬은 적용했나요?
- [x]  새로운 branch에 작업 후 dev로 PR을 요청했나요?

## 📝 작업 내용

- 커서 기반 페이지네이션 쿼리 구현
- 마이 커밋 조회 api 구현

- 테스트
<img width="479" alt="image" src="https://github.com/DKU-Dgaja/gitudy/assets/62228433/2cf609a4-e3d7-4cb0-b323-44ed4214fafa">

## 💬 리뷰 요구사항
- 테스트 케이스 빼먹은 거나 구현이 이상한 부분 있으면 알려주세요!

2024-02-04 13:30 UTC, ghdcksgml1 requested changes
👍

2024-02-04 13:30 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryImpl.java
> +        }
굳굳~~

2024-02-04 13:30 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java
> +        Long nextCursorIdx = null;
null보다는 디폴트가 0이니까 0으로 설정하는게 낫지않을까요??

2024-02-04 13:30 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java
> +                                        @Min(value = 0, message = "Cursor index cannot be negative") @RequestParam(name = "cursorIdx") Long cursorIdx) {
limit도 requestparam으로 받을 수 있게 하면 어떨까요? 

만약 프론트에서 30개로 늘려달라고하면, 애플리케이션 수정이 필요할 것 같아서 번거로울 것 같은데

2024-02-04 13:30 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/study/api/service/StudyCommitService.java
> +    private final static Long SELECT_COMMIT_LIST_LIMIT = 10L;
limit를 받고, MAX_LIMIT 가 넘어가는 요청에 대해서 거르기 or MAX_LIMIT로 만들기 처리만 해주심 될 것 같아요 ㅎㅎ

2024-02-04 13:55 UTC, jusung-c commented on backend/src/main/java/com/example/backend/study/api/service/StudyCommitService.java
> +    private final static Long SELECT_COMMIT_LIST_LIMIT = 10L;
MAX_LIMIT은 일단 50으로 해두겠습니다! 
추가로 limit 값에 @NotNull을 달아주는 게 좋을까요 아님 null인 경우 MAX_LIMIT으로 설정해주는 게 좋을까요?

2024-02-04 14:09 UTC, ghdcksgml1 commented on backend/src/main/java/com/example/backend/study/api/service/StudyCommitService.java
> +    private final static Long SELECT_COMMIT_LIST_LIMIT = 10L;
Default limit를 선언해두고 null일 경우 넣어주는 방법도 괜찮은 선택지일 것 같네요

2024-02-07 05:14 UTC, j-ra1n approved these changes

2024-02-13 01:11 UTC, jusung-c commented
마이페이지 - 마이 커밋 페이지
스터디별 커밋 조회 기능 추가했습니다!

2024-02-25 06:47 UTC, ghdcksgml1 approved these changes

2024-02-25 07:02 UTC, merged